// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvskbWXPcDO9RtyfNLBl8YKPT8rKrrlY',
    appId: '1:373074661731:web:cf9cac8b95a7fe91174356',
    messagingSenderId: '373074661731',
    databaseURL: "https://elearning-6c0ee-default-rtdb.firebaseio.com/",
    projectId: 'elearning-6c0ee',
    authDomain: 'elearning-6c0ee.firebaseapp.com',
    storageBucket: 'elearning-6c0ee.firebasestorage.app',
    measurementId: 'G-WYQ4CRFDH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7UI6OscxJRN7Wx_pj0kjz9nl1gOVDME',
    appId: '1:373074661731:android:511c9af0cc44db19174356',
    messagingSenderId: '373074661731',
    projectId: 'elearning-6c0ee',
    storageBucket: 'elearning-6c0ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3IV2jwvBKUPm8VWtT4KrF5_7RwD5lQcc',
    appId: '1:373074661731:ios:703577dcc1446fb4174356',
    messagingSenderId: '373074661731',
    projectId: 'elearning-6c0ee',
    storageBucket: 'elearning-6c0ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3IV2jwvBKUPm8VWtT4KrF5_7RwD5lQcc',
    appId: '1:373074661731:ios:703577dcc1446fb4174356',
    messagingSenderId: '373074661731',
    projectId: 'elearning-6c0ee',
    storageBucket: 'elearning-6c0ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvskbWXPcDO9RtyfNLBl8YKPT8rKrrlY',
    appId: '1:373074661731:web:0bfbebb296d9d745174356',
    messagingSenderId: '373074661731',
    projectId: 'elearning-6c0ee',
    authDomain: 'elearning-6c0ee.firebaseapp.com',
    storageBucket: 'elearning-6c0ee.firebasestorage.app',
    measurementId: 'G-JDGJN18JJ1',
  );

}